[package]
name = "sistemedic_bot"
version = "0.1.0"
authors = ["Bruno A. Muciño <mucinoab@gmail.com>"]
edition = "2018"

[dependencies]
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git" }
log = "0.4.11"
deunicode = "1.1.1"
log4rs = "1.0.0"
smol= "1.2.5"
async-compat = "0.1.4"
postgres = "0.18.1"
smartstring = "0.2.5"
smallvec = { version = "1.5.0", features = ["union", "specialization", "const_generics"] }
indexmap = "1.6.0"
hashbrown = { version = "0.9.1", features = ["nightly"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic="abort"
