[package]
name = "sistemedic_bot"
version = "0.1.0"
authors = ["Bruno A. Muciño <mucinoab@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.9"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git" }
log = "0.4.11"
deunicode = "1.1.1"
log4rs = "0.13.0"
once_cell = "1.4.1"
smol= "1.2.4"
async-compat = "0.1.4"
postgres = "0.17.5"
smartstring = "0.2.5"
smallvec = { version = "1.4.2", features = ["union", "specialization", "const_generics"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic="abort"
