[package]
name = "sistemedic_bot"
version = "0.1.0"
authors = ["Bruno A. Muciño <mucinoab@gmail.com>"]
edition = "2018"

[dependencies]
roman = "0.1.6"
regex = "1.3.9"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git" }
futures = "0.3.6"
tokio = { version = "0.2.22", features = ["rt-core", "macros"] }
log = "0.4.11"
deunicode = "1.1.1"
log4rs = "0.13.0"
once_cell = "1.4.1"
sqlx = { version = "0.3.5", default-features = false, features = [ "runtime-tokio", "postgres"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
