[package]
name = "sistemedic_bot"
version = "0.1.0"
authors = ["Bruno Muciño <mucinoab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roman = "0.1.6"
regex = "1.3.9"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git" }
futures = "0.3.5"
tokio = { version = "0.2", features = ["full"] }
lazy_static = "1.4.0"
tokio-postgres = "0.5.5"
log = "0.4.11"
deunicode = "1.1.1"
log4rs = "0.13.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[[bench]]
name = "ffast"
harness = false
