[package]
name = "sistemedic_bot"
version = "0.1.0"
authors = ["Bruno A. Muciño <mucinoab@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
telegram-bot = "0.8.0"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
futures = "0.3.17"
log = "0.4.14"
deunicode = "1.3.1"
log4rs = "1.0.0"
tokio-postgres = "0.7.4"
indexmap = "1.8.1"

[profile.dev]
debug = false

[profile.release]
lto = "fat"
codegen-units = 1
panic="abort"
